"""Generate the arXiv preprint (AMS `amsart` layout) from the SciPost userguide.

scipost/paper.tex is the single source of the text. This script copies its
abstract, body, statements and appendix verbatim into an `amsart` wrapper
(the layout of mathematics preprints on arXiv, e.g. math.QA), so that the two
versions cannot drift apart. The only changes to the text are the ones the
layout requires:

* \\mathbb{1} (a mathdesign glyph) becomes \\mathds{1} (dsfont);
* \\paragraph headings become italic run-in headings (\\emph{...});
* the SciPost back-matter paragraphs become an amsart "Declarations" section;
* the bibliography uses amsplain, which does not print the `doi` field, so a
  copy of references.bib is written with each DOI repeated in `note`.

Outputs (all generated, do not edit): arxiv/paper.tex, arxiv/references.bib,
arxiv/figures/figure1_workflow.pdf. Run from anywhere:
    python3 arxiv/build.py
"""
import pathlib
import re
import shutil

here = pathlib.Path(__file__).resolve().parent
src_dir = here.parent / "scipost"
src = (src_dir / "paper.tex").read_text(encoding="utf-8")


def between(text, start, end, include_start=True):
    i = text.index(start)
    j = text.index(end, i + len(start))
    return text[i if include_start else i + len(start):j]


def body_text(text):
    # amsart's \paragraph is set in the body font without emphasis; use an
    # italic run-in heading (as for "Proof.") with a small skip instead.
    text = re.sub(r"\\paragraph\{", r"\\par\\needspace{3\\baselineskip}\\smallskip\\noindent\\emph{", text)
    return text.replace(r"\mathbb{1}", r"\mathds{1}")


preamble = between(src, r"\usepackage[T1]{fontenc}", r"\captionsetup[lstlisting]")
# xurl breaks URLs inside words; the url package (loaded by hyperref) breaks
# them only after "/", "." and "-", which reads better in references.
preamble = preamble.replace("\\usepackage{xurl}\n", "")
abstract = between(src, "\\textbf{\\boldmath{%\n", "\n}}", include_start=False).strip()
body = between(src, r"\section{Introduction}", r"\section*{Acknowledgements}").rstrip()
appendix = between(src, r"\section{Reference of the public interface}", r"\end{appendix}").rstrip()
acknowledgements = between(src, "\\section*{Acknowledgements}\n", "\n", include_start=False).strip()


def statement(title):
    m = re.search(r"\\paragraph\{%s\}\n(.+?)\n" % re.escape(title), src)
    return m.group(1).strip()


statements = [
    ("Author contributions", statement("Author contributions")),
    ("Funding", statement("Funding information")),
    ("Competing interests", statement("Competing interests")),
    ("Code and data availability",
     r"The software, the scripts of all listings with their expected outputs "
     r"and the exported QuaGroup data are in the repository and its release "
     r"archive; see the paragraph \emph{Code availability} in "
     r"Section~\ref{sec:install}."),
    ("Use of generative AI", statement("Use of generative AI")),
]

title = (r"\qgname: Exact symbolic verification of "
         r"R-matrix and Yang--Baxter identities for $U_q(\mathfrak{sl}_2)$ and "
         r"$GL_q(2|1)$")
short_title = r"\qgname: exact verification of R-matrix identities"

tex = r"""%% GENERATED by arxiv/build.py from scipost/paper.tex -- do not edit by hand.
%% arXiv preprint of the userguide of quantum-group, in the AMS amsart layout.
%% Build: make -C arxiv   (pdflatex, bibtex, pdflatex x2)
\documentclass{amsart}

\usepackage{amssymb}
\usepackage{needspace}
\usepackage{dsfont}
\usepackage{xcolor}
\usepackage{graphicx}
\usepackage{hyperref}
\hypersetup{colorlinks, linkcolor={red!50!black}, citecolor={blue!50!black},
  urlcolor={blue!80!black}}
\usepackage{doi}

\binoppenalty=10000
\relpenalty=10000
\urlstyle{same}

""" + preamble.rstrip() + r"""
% amsart sets a caption that does not fit on one line as a justified
% paragraph, which spreads listing captions ending in long file names; the
% caption package (which supports the AMS classes) keeps the amsart look and
% centres the listing captions, as in the SciPost version.
\usepackage[labelfont=sc, labelsep=period, font=small]{caption}
\captionsetup[lstlisting]{justification=centering}

% Bracketed reference labels, [1], as in the text citations (amsart's
% default with amsplain is "1.").
\makeatletter
\def\@defaultbiblabelstyle#1{[#1]}
\makeatother

% Subsection headings on a line of their own: amsart's run-in bold headings
% are stretched badly when they are long and contain mathematics.
\makeatletter
\renewcommand\subsection{\@startsection{subsection}{2}{\z@}%
  {.7\linespacing\@plus\linespacing}{.3\linespacing}{\normalfont\bfseries}}
\makeatother

% The amsart text block is narrower than SciPost's; allow more interword
% stretch so paragraphs with long identifiers do not overflow.
\setlength{\emergencystretch}{8em}

% amsart upper-cases the title and running head; a robust command keeps the
% package name in lower case.
\DeclareRobustCommand{\qgname}{\texttt{quantum-group}}

\hypersetup{pdftitle={quantum-group: Exact symbolic verification of R-matrix and Yang-Baxter identities for Uq(sl2) and GLq(2|1)},
  pdfauthor={Taha Berk Terekli}}

\begin{document}

\title[""" + short_title + "]{" + title + r"""}

\author{Taha Berk Terekli}
\address{Department of Mathematics, Y{\i}ld{\i}z Technical University, Istanbul, T\"urkiye}
\email{terekli@tahaberk.com}
\urladdr{https://orcid.org/0009-0004-8266-1116}

\subjclass[2020]{Primary 17B37; Secondary 16T25, 81R50, 68W30}
\keywords{Quantum groups, R-matrix, Yang--Baxter equation, quantum supergroups, Koszul sign rule, exact symbolic computation, SymPy}

\begin{abstract}
""" + body_text(abstract) + r"""
\end{abstract}

\maketitle

""" + body_text(body) + r"""

\section*{Acknowledgments}

""" + acknowledgements + r"""

\section*{Declarations}

""" + "\n\n\\medskip\n".join(r"\noindent\textbf{%s:} %s" % (k, body_text(v)) for k, v in statements) + r"""

\appendix

""" + body_text(appendix) + r"""

\bibliographystyle{amsplain}
\bibliography{references}

\end{document}
"""
(here / "paper.tex").write_text(tex, encoding="utf-8")

# Bibliography: repeat each DOI in `note`, which amsplain prints.
bib = (src_dir / "references.bib").read_text(encoding="utf-8")
out = []
for entry in re.split(r"(?m)^(?=@)", bib):
    if not entry.startswith("@"):
        continue  # the source file's comment header describes the SciPost style
    # amsplain prints `note` before `pages`; keep the pages before a URL note.
    pages = re.search(r"(?m)^\s*pages\s*=\s*\{([^}]*)\},?\n", entry)
    urlnote = re.search(r"(?m)^(\s*note\s*=\s*\{)(\\url\{[^}]*\})\}", entry)
    if pages and urlnote:
        entry = entry.replace(urlnote.group(0), urlnote.group(1) + "pp.~" + pages.group(1) + ", " + urlnote.group(2) + "}")
        entry = entry.replace(pages.group(0), "")
    doi = re.search(r"(?m)^\s*doi\s*=\s*\{([^}]*)\}", entry)
    if entry.startswith("@") and doi:
        link = r"\doi{%s}" % doi.group(1)
        note = re.search(r"(?m)^(\s*note\s*=\s*\{)(.*)\}(,?)\s*$", entry)
        if note:
            entry = entry[:note.start()] + note.group(1) + note.group(2) + ", " + link + "}" + note.group(3) + entry[note.end():]
        else:
            entry = re.sub(r"(?m)^(\s*doi\s*=\s*\{[^}]*\})(,?)", r"\1,\n  note         = {%s}\2" % link.replace("\\", "\\\\"), entry, count=1)
    out.append(entry)
header = "% GENERATED by arxiv/build.py from scipost/references.bib -- do not edit.\n\n"
(here / "references.bib").write_text(header + "".join(out), encoding="utf-8")

(here / "figures").mkdir(exist_ok=True)
shutil.copyfile(src_dir / "figures" / "figure1_workflow.pdf", here / "figures" / "figure1_workflow.pdf")
print("wrote arxiv/paper.tex, arxiv/references.bib, arxiv/figures/figure1_workflow.pdf")
